// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
// AUTOGENERATED by tools/codegen/emit_csharp.py — DO NOT EDIT.

using System.Runtime.InteropServices;
using Whiteout.Common;
using Whiteout.Casc.Internal;

namespace Whiteout.Casc;

/// <summary>Unified read-only CASC storage (local disk or CDN)</summary>
public sealed class Storage : WhiteoutHandle
{
    internal Storage(IntPtr handle, bool owned = true) : base(handle, owned) { }

    protected override bool ReleaseHandle()
    {
        NativeMethods.whiteout_casc_CascStorage_delete(handle);
        return true;
    }

    /// <summary>@return True if this storage reads from local disk.</summary>
    public bool IsLocal
    {
        get => NativeMethods.whiteout_casc_CascStorage_isLocal(DangerousGet()) != 0;
    }


    /// <summary>@return True if this storage reads from CDN.</summary>
    public bool IsOnline
    {
        get => NativeMethods.whiteout_casc_CascStorage_isOnline(DangerousGet()) != 0;
    }


    /// <summary>@return True if this storage has a write overlay (StorageWritable).</summary>
    public bool IsWritable
    {
        get => NativeMethods.whiteout_casc_CascStorage_isWritable(DangerousGet()) != 0;
    }


    /// <summary>@return The root manifest format, or RootFormat::Unknown.</summary>
    public RootFormat RootFormat
    {
        get => (RootFormat)NativeMethods.whiteout_casc_CascStorage_rootFormat(DangerousGet());
    }


    /// <summary>Open an existing local CASC storage. @param path Path to the game's top-level directory (containing .build.info) or its Data subdirectory. @param pool Optional WorkerPool for parallel I/O (non-owning). @return A valid Storage, or std::nullopt on failure.</summary>
    public static Storage? Open(string path, Whiteout.Host.WorkerPool pool)
    {
        var __h = NativeMethods.whiteout_casc_CascStorage_open(path, pool.DangerousGet());
        return __h == IntPtr.Zero ? null : new Storage(__h);
    }


    /// <summary>@overload Open with locale mask.</summary>
    public static Storage? OpenPathLocaleMaskPool(string path, uint localeMask, Whiteout.Host.WorkerPool pool)
    {
        var __h = NativeMethods.whiteout_casc_CascStorage_open_path_localeMask_pool(path, localeMask, pool.DangerousGet());
        return __h == IntPtr.Zero ? null : new Storage(__h);
    }


    /// <summary>Release all resources and invalidate the storage.</summary>
    public new void Close()
    {
        NativeMethods.whiteout_casc_CascStorage_close(DangerousGet());
    }


    /// <summary>@return File contents, or std::nullopt if the path is not found.</summary>
    public byte[]? ReadFile(string cascPath)
    {
        var __b = NativeMethods.whiteout_casc_CascStorage_readFile(DangerousGet(), cascPath);
        return __b.IsEmpty ? null : __b.ToManagedArray();
    }


    /// <summary>@overload Read a file by path with locale and open flags.</summary>
    public byte[]? ReadFileCascPathLocaleFlagsOpenFlags(string cascPath, uint localeFlags, uint openFlags)
    {
        var __b = NativeMethods.whiteout_casc_CascStorage_readFile_cascPath_localeFlags_openFlags(DangerousGet(), cascPath, localeFlags, openFlags);
        return __b.IsEmpty ? null : __b.ToManagedArray();
    }


    /// <summary>@overload Read a file by WoW-style FileDataId.</summary>
    public byte[]? ReadFileFileIdHint(int fileId, FileIdHint hint)
    {
        var __b = NativeMethods.whiteout_casc_CascStorage_readFile_fileId_hint(DangerousGet(), fileId, (int)hint);
        return __b.IsEmpty ? null : __b.ToManagedArray();
    }


    /// <summary>@overload Read a file by FileDataId with locale and open flags.</summary>
    public byte[]? ReadFileFileIdLocaleFlagsOpenFlagsHint(int fileId, uint localeFlags, uint openFlags, FileIdHint hint)
    {
        var __b = NativeMethods.whiteout_casc_CascStorage_readFile_fileId_localeFlags_openFlags_hint(DangerousGet(), fileId, localeFlags, openFlags, (int)hint);
        return __b.IsEmpty ? null : __b.ToManagedArray();
    }


    /// <summary>@return True if the path resolves to a known file.</summary>
    public bool FileExists(string cascPath)
    {
        return NativeMethods.whiteout_casc_CascStorage_fileExists(DangerousGet(), cascPath) != 0;
    }


    /// <summary>@overload Check existence by FileDataId.</summary>
    public bool FileExistsFileIdHint(int fileId, FileIdHint hint)
    {
        return NativeMethods.whiteout_casc_CascStorage_fileExists_fileId_hint(DangerousGet(), fileId, (int)hint) != 0;
    }


    /// <summary>@return All known file paths.</summary>
    public IReadOnlyList<string> ListFiles =>
        new NativeListView<string>(
            DangerousGet(),
            NativeMethods.whiteout_casc_CascStorage_listFiles_count,
            (h, i) => NativeMethods.whiteout_casc_CascStorage_listFiles_at(h, i).ToManagedString());

    /// <summary>@return Known file paths under a path prefix.</summary>
    public IReadOnlyList<string> ListFilesPrefix(string prefix) =>
        new NativeListView<string>(
            DangerousGet(),
            h => NativeMethods.whiteout_casc_CascStorage_listFilesPrefix_count(h, prefix),
            (h, i) => NativeMethods.whiteout_casc_CascStorage_listFilesPrefix_at(h, prefix, i).ToManagedString());

    /// <summary>@return Uncompressed file sizes for known file paths under a path prefix.</summary>
    public IReadOnlyList<ulong> ListFilesPrefixSizes(string prefix) =>
        new NativeListView<ulong>(
            DangerousGet(),
            h => NativeMethods.whiteout_casc_CascStorage_listFilesPrefix_count(h, prefix),
            (h, i) => NativeMethods.whiteout_casc_CascStorage_listFilesPrefix_size_at(h, prefix, i));


    /// <summary>Import encryption keys from a formatted string (one per line).</summary>
    public bool ImportKeysFromString(string keyList)
    {
        return NativeMethods.whiteout_casc_CascStorage_importKeysFromString(DangerousGet(), keyList) != 0;
    }


    /// <summary>Import encryption keys from a file.</summary>
    public bool ImportKeysFromFile(string keyFilePath)
    {
        return NativeMethods.whiteout_casc_CascStorage_importKeysFromFile(DangerousGet(), keyFilePath) != 0;
    }


    /// <summary>Clear the in-memory decoded-data cache (container cache).</summary>
    public void FlushCache()
    {
        NativeMethods.whiteout_casc_CascStorage_flushCache(DangerousGet());
    }


    /// <summary>Force every deferred load (encoding, root, VFS, index files, orphan bitvector) to resolve. Idempotent.</summary>
    public bool Prefetch()
    {
        return NativeMethods.whiteout_casc_CascStorage_prefetch(DangerousGet()) != 0;
    }


    /// <summary>@return Last error code (thread-local).</summary>
    public static uint LastError()
    {
        return NativeMethods.whiteout_casc_CascStorage_lastError();
    }

}
