// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
// AUTOGENERATED by tools/codegen/emit_c.py — do not edit.
// Regenerate via:  python -m tools.codegen.codegen casc --backend c-source

#include "whiteout_casc.h"

#include <cstring>
#include <cstdint>
#include <new>
#include <span>
#include <string>
#include <unordered_map>
#include <vector>

#include <whiteout/storages/casc/types.h>
#include <whiteout/storages/casc/storage.h>
#include <whiteout/storages/casc/storage_writable.h>

namespace { using namespace whiteout; }

namespace {

// `whiteout::u8` is `std::uint8_t`, so a single overload suffices. We use
// the project's type so the reinterpret_cast is a no-op everywhere the
// codegen runs.
inline whiteout_Bytes wrapBytes(std::vector<whiteout::u8>&& v) {
    auto* owned = new std::vector<whiteout::u8>(std::move(v));
    return { reinterpret_cast<const uint8_t*>(owned->data()), owned->size(), owned };
}

inline whiteout_Bytes emptyBytes() {
    return { nullptr, 0, nullptr };
}

inline whiteout_CString wrapCString(std::string&& s) {
    auto* owned = new std::string(std::move(s));
    return { owned->c_str(), owned->size(), owned };
}

inline whiteout_CString emptyCString() {
    return { nullptr, 0, nullptr };
}

using CascStorageNative = whiteout::storages::casc::Storage;

struct CachedCascFileEntry {
    std::string path;
    std::uint64_t fileSize = 0;
};

thread_local std::unordered_map<const CascStorageNative*, std::vector<std::string>> g_cascListFilesCache;
thread_local std::unordered_map<std::string, std::vector<CachedCascFileEntry>> g_cascListFilesPrefixCache;

const std::vector<std::string>& cachedListFiles(const CascStorageNative* storage, bool refresh) {
    auto it = g_cascListFilesCache.find(storage);
    if (refresh || it == g_cascListFilesCache.end()) {
        it = g_cascListFilesCache.insert_or_assign(storage, storage->listFiles()).first;
    }
    return it->second;
}

std::string prefixCacheKey(const CascStorageNative* storage, std::string_view prefix) {
    std::string key;
    key.reserve(32 + prefix.size());
    key += std::to_string(reinterpret_cast<std::uintptr_t>(storage));
    key.push_back('\0');
    key.append(prefix.data(), prefix.size());
    return key;
}

std::string normalizePrefixArg(const char* prefix) {
    std::string out(prefix ? prefix : "");
    while (!out.empty() && (out.front() == '/' || out.front() == '\\')) out.erase(out.begin());
    while (!out.empty() && (out.back() == '/' || out.back() == '\\')) out.pop_back();
    for (char& ch : out) {
        if (ch == '\\') ch = '/';
        else if (ch >= 'A' && ch <= 'Z') ch = static_cast<char>(ch + 32);
    }
    return out;
}

bool startsWithPrefixPath(std::string_view path, std::string_view prefix) {
    if (path.size() < prefix.size()) return false;
    for (size_t i = 0; i < prefix.size(); ++i) {
        char ch = path[i];
        if (ch == '\\') ch = '/';
        else if (ch >= 'A' && ch <= 'Z') ch = static_cast<char>(ch + 32);
        if (ch != prefix[i]) return false;
    }
    return path.size() == prefix.size() || path[prefix.size()] == '/' || path[prefix.size()] == '\\';
}

const std::vector<CachedCascFileEntry>& cachedListFilesPrefix(const CascStorageNative* storage, const char* rawPrefix, bool refresh) {
    std::string const prefix = normalizePrefixArg(rawPrefix);
    std::string const key = prefixCacheKey(storage, prefix);
    auto it = g_cascListFilesPrefixCache.find(key);
    if (refresh || it == g_cascListFilesPrefixCache.end()) {
        std::vector<CachedCascFileEntry> files;
        storage->enumerate(prefix + "/*", [&](const whiteout::storages::casc::EnumerateEntry& entry) {
            if (!entry.path.empty() && startsWithPrefixPath(entry.path, prefix))
                files.push_back({ std::string(entry.path), entry.fileSize });
            return true;
        });
        it = g_cascListFilesPrefixCache.insert_or_assign(key, std::move(files)).first;
    }
    return it->second;
}

} // anonymous

// ── CascCreateOptions ─────────────────────────────────────────────────

extern "C" {

whiteout_CascCreateOptions* whiteout_casc_CascCreateOptions_new(void) {
    return reinterpret_cast<whiteout_CascCreateOptions*>(new whiteout::storages::casc::CreateOptions());
}

void whiteout_casc_CascCreateOptions_delete(whiteout_CascCreateOptions* self) {
    delete reinterpret_cast<whiteout::storages::casc::CreateOptions*>(self);
}

whiteout_CString whiteout_casc_CascCreateOptions_get_product(const whiteout_CascCreateOptions* self) {
    auto* __owned = new std::string(reinterpret_cast<const whiteout::storages::casc::CreateOptions*>(self)->product);
    return whiteout_CString{ __owned->c_str(), __owned->size(), __owned };
}

void whiteout_casc_CascCreateOptions_set_product(whiteout_CascCreateOptions* self, const char* value) {
    reinterpret_cast<whiteout::storages::casc::CreateOptions*>(self)->product = (value ? value : "");
}

whiteout_CString whiteout_casc_CascCreateOptions_get_version(const whiteout_CascCreateOptions* self) {
    auto* __owned = new std::string(reinterpret_cast<const whiteout::storages::casc::CreateOptions*>(self)->version);
    return whiteout_CString{ __owned->c_str(), __owned->size(), __owned };
}

void whiteout_casc_CascCreateOptions_set_version(whiteout_CascCreateOptions* self, const char* value) {
    reinterpret_cast<whiteout::storages::casc::CreateOptions*>(self)->version = (value ? value : "");
}

uint32_t whiteout_casc_CascCreateOptions_get_archiveMaxSize(const whiteout_CascCreateOptions* self) {
    return reinterpret_cast<const whiteout::storages::casc::CreateOptions*>(self)->archiveMaxSize;
}

void whiteout_casc_CascCreateOptions_set_archiveMaxSize(whiteout_CascCreateOptions* self, uint32_t value) {
    reinterpret_cast<whiteout::storages::casc::CreateOptions*>(self)->archiveMaxSize = value;
}

uint32_t whiteout_casc_CascCreateOptions_get_blteFrameSize(const whiteout_CascCreateOptions* self) {
    return reinterpret_cast<const whiteout::storages::casc::CreateOptions*>(self)->blteFrameSize;
}

void whiteout_casc_CascCreateOptions_set_blteFrameSize(whiteout_CascCreateOptions* self, uint32_t value) {
    reinterpret_cast<whiteout::storages::casc::CreateOptions*>(self)->blteFrameSize = value;
}

int32_t whiteout_casc_CascCreateOptions_get_rootFormat(const whiteout_CascCreateOptions* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::storages::casc::CreateOptions*>(self)->rootFormat);
}

void whiteout_casc_CascCreateOptions_set_rootFormat(whiteout_CascCreateOptions* self, int32_t value) {
    reinterpret_cast<whiteout::storages::casc::CreateOptions*>(self)->rootFormat = static_cast<whiteout::storages::casc::RootFormat>(value);
}

} // extern "C"

// ── CascWriteOptions ─────────────────────────────────────────────────

extern "C" {

whiteout_CascWriteOptions* whiteout_casc_CascWriteOptions_new(void) {
    return reinterpret_cast<whiteout_CascWriteOptions*>(new whiteout::storages::casc::WriteOptions());
}

void whiteout_casc_CascWriteOptions_delete(whiteout_CascWriteOptions* self) {
    delete reinterpret_cast<whiteout::storages::casc::WriteOptions*>(self);
}

uint32_t whiteout_casc_CascWriteOptions_get_localeFlags(const whiteout_CascWriteOptions* self) {
    return reinterpret_cast<const whiteout::storages::casc::WriteOptions*>(self)->localeFlags;
}

void whiteout_casc_CascWriteOptions_set_localeFlags(whiteout_CascWriteOptions* self, uint32_t value) {
    reinterpret_cast<whiteout::storages::casc::WriteOptions*>(self)->localeFlags = value;
}

uint32_t whiteout_casc_CascWriteOptions_get_contentFlags(const whiteout_CascWriteOptions* self) {
    return reinterpret_cast<const whiteout::storages::casc::WriteOptions*>(self)->contentFlags;
}

void whiteout_casc_CascWriteOptions_set_contentFlags(whiteout_CascWriteOptions* self, uint32_t value) {
    reinterpret_cast<whiteout::storages::casc::WriteOptions*>(self)->contentFlags = value;
}

int32_t whiteout_casc_CascWriteOptions_get_compress(const whiteout_CascWriteOptions* self) {
    return reinterpret_cast<const whiteout::storages::casc::WriteOptions*>(self)->compress;
}

void whiteout_casc_CascWriteOptions_set_compress(whiteout_CascWriteOptions* self, int32_t value) {
    reinterpret_cast<whiteout::storages::casc::WriteOptions*>(self)->compress = value;
}

} // extern "C"

// ── CascStorage ─────────────────────────────────────────────────

extern "C" {

void whiteout_casc_CascStorage_delete(whiteout_CascStorage* self) {
    auto* storage = reinterpret_cast<whiteout::storages::casc::Storage*>(self);
    g_cascListFilesCache.erase(storage);
    for (auto it = g_cascListFilesPrefixCache.begin(); it != g_cascListFilesPrefixCache.end();) {
        if (it->first.rfind(std::to_string(reinterpret_cast<std::uintptr_t>(storage)) + '\0', 0) == 0)
            it = g_cascListFilesPrefixCache.erase(it);
        else
            ++it;
    }
    delete storage;
}

struct whiteout_CascStorage* whiteout_casc_CascStorage_open(const char* path, void* pool) {
    auto __r = whiteout::storages::casc::Storage::open(std::string(path ? path : ""), reinterpret_cast<whiteout::interfaces::WorkerPool*>(pool));
    if (!__r) return nullptr;
    return reinterpret_cast<struct whiteout_CascStorage*>(
        new whiteout::storages::casc::Storage(std::move(*__r)));
}

struct whiteout_CascStorage* whiteout_casc_CascStorage_open_path_localeMask_pool(const char* path, uint32_t localeMask, void* pool) {
    auto __r = whiteout::storages::casc::Storage::open(std::string(path ? path : ""), localeMask, reinterpret_cast<whiteout::interfaces::WorkerPool*>(pool));
    if (!__r) return nullptr;
    return reinterpret_cast<struct whiteout_CascStorage*>(
        new whiteout::storages::casc::Storage(std::move(*__r)));
}

void whiteout_casc_CascStorage_close(whiteout_CascStorage* self) {
    reinterpret_cast<whiteout::storages::casc::Storage*>(self)->close();
}

int32_t whiteout_casc_CascStorage_isLocal(const whiteout_CascStorage* self) {
    return reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->isLocal();
}

int32_t whiteout_casc_CascStorage_isOnline(const whiteout_CascStorage* self) {
    return reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->isOnline();
}

int32_t whiteout_casc_CascStorage_isWritable(const whiteout_CascStorage* self) {
    return reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->isWritable();
}

int32_t whiteout_casc_CascStorage_rootFormat(const whiteout_CascStorage* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->rootFormat());
}

whiteout_Bytes whiteout_casc_CascStorage_readFile(const whiteout_CascStorage* self, const char* cascPath) {
    auto __r = reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->readFile(std::string(cascPath ? cascPath : ""));
    if (!__r) return emptyBytes();
    return wrapBytes(std::move(*__r));
}

whiteout_Bytes whiteout_casc_CascStorage_readFile_cascPath_localeFlags_openFlags(const whiteout_CascStorage* self, const char* cascPath, uint32_t localeFlags, uint32_t openFlags) {
    auto __r = reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->readFile(std::string(cascPath ? cascPath : ""), localeFlags, openFlags);
    if (!__r) return emptyBytes();
    return wrapBytes(std::move(*__r));
}

whiteout_Bytes whiteout_casc_CascStorage_readFile_fileId_hint(const whiteout_CascStorage* self, int32_t fileId, int32_t hint) {
    auto __r = reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->readFile(fileId, static_cast<whiteout::storages::casc::FileIdHint>(hint));
    if (!__r) return emptyBytes();
    return wrapBytes(std::move(*__r));
}

whiteout_Bytes whiteout_casc_CascStorage_readFile_fileId_localeFlags_openFlags_hint(const whiteout_CascStorage* self, int32_t fileId, uint32_t localeFlags, uint32_t openFlags, int32_t hint) {
    auto __r = reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->readFile(fileId, localeFlags, openFlags, static_cast<whiteout::storages::casc::FileIdHint>(hint));
    if (!__r) return emptyBytes();
    return wrapBytes(std::move(*__r));
}

int32_t whiteout_casc_CascStorage_fileExists(const whiteout_CascStorage* self, const char* cascPath) {
    return reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->fileExists(std::string(cascPath ? cascPath : ""));
}

int32_t whiteout_casc_CascStorage_fileExists_fileId_hint(const whiteout_CascStorage* self, int32_t fileId, int32_t hint) {
    return reinterpret_cast<const whiteout::storages::casc::Storage*>(self)->fileExists(fileId, static_cast<whiteout::storages::casc::FileIdHint>(hint));
}

size_t whiteout_casc_CascStorage_listFiles_count(const whiteout_CascStorage* self) {
    return cachedListFiles(reinterpret_cast<const whiteout::storages::casc::Storage*>(self), true).size();
}

whiteout_CString whiteout_casc_CascStorage_listFiles_at(const whiteout_CascStorage* self, size_t index) {
    const auto& __v = cachedListFiles(reinterpret_cast<const whiteout::storages::casc::Storage*>(self), false);
    if (index >= __v.size()) return emptyCString();
    return wrapCString(std::string(__v[index]));
}

size_t whiteout_casc_CascStorage_listFilesPrefix_count(const whiteout_CascStorage* self, const char* prefix) {
    return cachedListFilesPrefix(reinterpret_cast<const whiteout::storages::casc::Storage*>(self), prefix, true).size();
}

whiteout_CString whiteout_casc_CascStorage_listFilesPrefix_at(const whiteout_CascStorage* self, const char* prefix, size_t index) {
    const auto& __v = cachedListFilesPrefix(reinterpret_cast<const whiteout::storages::casc::Storage*>(self), prefix, false);
    if (index >= __v.size()) return emptyCString();
    return wrapCString(std::string(__v[index].path));
}

uint64_t whiteout_casc_CascStorage_listFilesPrefix_size_at(const whiteout_CascStorage* self, const char* prefix, size_t index) {
    const auto& __v = cachedListFilesPrefix(reinterpret_cast<const whiteout::storages::casc::Storage*>(self), prefix, false);
    if (index >= __v.size()) return 0;
    return __v[index].fileSize;
}

int32_t whiteout_casc_CascStorage_importKeysFromString(whiteout_CascStorage* self, const char* keyList) {
    return reinterpret_cast<whiteout::storages::casc::Storage*>(self)->importKeysFromString(std::string(keyList ? keyList : ""));
}

int32_t whiteout_casc_CascStorage_importKeysFromFile(whiteout_CascStorage* self, const char* keyFilePath) {
    return reinterpret_cast<whiteout::storages::casc::Storage*>(self)->importKeysFromFile(std::string(keyFilePath ? keyFilePath : ""));
}

void whiteout_casc_CascStorage_flushCache(whiteout_CascStorage* self) {
    reinterpret_cast<whiteout::storages::casc::Storage*>(self)->flushCache();
}

int32_t whiteout_casc_CascStorage_prefetch(whiteout_CascStorage* self) {
    return reinterpret_cast<whiteout::storages::casc::Storage*>(self)->prefetch();
}

uint32_t whiteout_casc_CascStorage_lastError(void) {
    return whiteout::storages::casc::Storage::lastError();
}

} // extern "C"

// ── CascStorageWritable ─────────────────────────────────────────────────

extern "C" {

void whiteout_casc_CascStorageWritable_delete(whiteout_CascStorageWritable* self) {
    delete reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self);
}

struct whiteout_CascStorageWritable* whiteout_casc_CascStorageWritable_create(struct whiteout_CascCreateOptions* opts, void* pool) {
    return reinterpret_cast<struct whiteout_CascStorageWritable*>(
        new whiteout::storages::casc::StorageWritable(whiteout::storages::casc::StorageWritable::create(*reinterpret_cast<const whiteout::storages::casc::CreateOptions*>(opts), reinterpret_cast<whiteout::interfaces::WorkerPool*>(pool))));
}

int32_t whiteout_casc_CascStorageWritable_writeFile(whiteout_CascStorageWritable* self, const char* path, const uint8_t* data, size_t data_size, struct whiteout_CascWriteOptions* opts) {
    return reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self)->writeFile(std::string(path ? path : ""), std::vector<whiteout::u8>(data, data + data_size), *reinterpret_cast<const whiteout::storages::casc::WriteOptions*>(opts));
}

int32_t whiteout_casc_CascStorageWritable_writeFile_fileId_data_opts_hint(whiteout_CascStorageWritable* self, int32_t fileId, const uint8_t* data, size_t data_size, struct whiteout_CascWriteOptions* opts, int32_t hint) {
    return reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self)->writeFile(fileId, std::vector<whiteout::u8>(data, data + data_size), *reinterpret_cast<const whiteout::storages::casc::WriteOptions*>(opts), static_cast<whiteout::storages::casc::FileIdHint>(hint));
}

int32_t whiteout_casc_CascStorageWritable_deleteFile(whiteout_CascStorageWritable* self, const char* path) {
    return reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self)->deleteFile(std::string(path ? path : ""));
}

int32_t whiteout_casc_CascStorageWritable_deleteFile_fileId_hint(whiteout_CascStorageWritable* self, int32_t fileId, int32_t hint) {
    return reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self)->deleteFile(fileId, static_cast<whiteout::storages::casc::FileIdHint>(hint));
}

int32_t whiteout_casc_CascStorageWritable_save(whiteout_CascStorageWritable* self) {
    return reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self)->save();
}

int32_t whiteout_casc_CascStorageWritable_save_path(whiteout_CascStorageWritable* self, const char* path) {
    return reinterpret_cast<whiteout::storages::casc::StorageWritable*>(self)->save(std::string(path ? path : ""));
}

} // extern "C"

